server:
  port: 8091
  servlet:
    context-path: /wh
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghuan?useSSL=false&amp;characterEncoding=utf-8&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: false
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:${image.location}
mybatis:
  mapper-locations: classpath:com/wh/demo/test/dao/mapper/*.xml
  type-aliases-package: com.wh.demo.test.model
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.wh: DEBUG
image:
  location: F:/myfile/image