server:
  port: 8090
  servlet:
    context-path: /wh
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghuan?useSSL=false&amp;characterEncoding=utf-8&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    
mybatis:
  mapper-locations: classpath:com/wh/demo/test/dao/mapper/*.xml
  type-aliases-package: com.wh.demo.test.model

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.wh: DEBUG
